# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ousam\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoAgent\geoagent_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeoAgentDockWidgetBase(object):
    def setupUi(self, GeoAgentDockWidgetBase):
        GeoAgentDockWidgetBase.setObjectName("GeoAgentDockWidgetBase")
        GeoAgentDockWidgetBase.resize(902, 409)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 26))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-radius: 5px;\n"
"    border: 1px solid #39394a;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.Send_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.Send_button.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #4a4f4d;\n"
"    padding: 6px;\n"
"     color: white;\n"
"}\n"
"\n"
"")
        self.Send_button.setObjectName("Send_button")
        self.horizontalLayout.addWidget(self.Send_button)
        self.Clear_button = QtWidgets.QPushButton(self.dockWidgetContents)
        self.Clear_button.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #4a4f4d;\n"
"    padding: 6px;\n"
"     color: white;\n"
"}\n"
"\n"
"")
        self.Clear_button.setObjectName("Clear_button")
        self.horizontalLayout.addWidget(self.Clear_button)
        self.line_2 = QtWidgets.QFrame(self.dockWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border-radius: 5px;\n"
"    background-color: #4a4f4d;\n"
"    padding: 6px;\n"
"     color: white;\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.line = QtWidgets.QFrame(self.dockWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.dockWidgetContents)
        self.textBrowser.setStyleSheet("#textBrowser {\n"
"    background-color: #adb8b4;\n"
"    border: 1px solid #39394a;\n"
"    border-radius: 12px;\n"
"    /*color: #d9dce0; */\n"
"    font-family: \'Segoe UI\', Arial, sans-serif;\n"
"    font-size: 14px;\n"
"    selection-background-color: #4a77b6;\n"
"    selection-color: white;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        GeoAgentDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(GeoAgentDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(GeoAgentDockWidgetBase)

    def retranslateUi(self, GeoAgentDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        GeoAgentDockWidgetBase.setWindowTitle(_translate("GeoAgentDockWidgetBase", "Geo Agent"))
        self.Send_button.setText(_translate("GeoAgentDockWidgetBase", "Send"))
        self.Clear_button.setText(_translate("GeoAgentDockWidgetBase", "Clear Chat"))
        self.label.setText(_translate("GeoAgentDockWidgetBase", "Models:"))
        self.comboBox.setItemText(0, _translate("GeoAgentDockWidgetBase", "Chat GPT"))
        self.comboBox.setItemText(1, _translate("GeoAgentDockWidgetBase", "Claude"))
        self.comboBox.setItemText(2, _translate("GeoAgentDockWidgetBase", "Gemini"))
        self.comboBox.setItemText(3, _translate("GeoAgentDockWidgetBase", "Perplexity"))
        self.comboBox.setItemText(4, _translate("GeoAgentDockWidgetBase", "Deepseek"))
